apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify-svc
spec:
  selector:
    matchLabels:
      app: notify-svc
  template:
    metadata:
      labels:
        app: notify-svc
    spec:
      containers:
        - name: notify-svc
          image: zakariabijoy/notify-svc
          imagePullPolicy: Never
          env:
            - name: RabbitMq__Host
              value: rabbit-clusterip
            - name: RabbitMq__Username
              value: admin
            - name: RabbitMq__Password
              value: b21525
---
apiVersion: v1
kind: Service
metadata:
  name: notify-clusterip
spec:
  type: ClusterIP
  selector:
    app: notify-svc
  ports:
    - port: 80
      targetPort: 80
